name: ingestion
services:
    # MQTT Ingestion Broker for provider 1
    hivemq1:
        image: hivemq/hivemq-ce
        container_name: ingestion-hivemq-broker1
        environment:
            - HIVEMQ_LOG_LEVEL=DEBUG
        ports:
            - 1883:1883
            - 8888:9399
        volumes:
            - ./monitoring/hivemq-prometheus-extension:/opt/hivemq/extensions/hivemq-prometheus-extension
            - ./monitoring/hivemq-file-rbac-extension:/opt/hivemq/extensions/hivemq-file-rbac-extension
            - ./scripts/credentials_ingestion.xml:/opt/hivemq/extensions/hivemq-file-rbac-extension/conf/credentials.xml
        ulimits:
            nofile:
                soft: 500000
                hard: 500000
    # MQTT Ingestion Broker for provider 2
    hivemq2:
        image: hivemq/hivemq-ce
        container_name: ingestion-hivemq-broker2
        environment:
            - HIVEMQ_LOG_LEVEL=DEBUG
        ports:
            - 1884:1883
            - 8889:9399
            - 8081:8080 # used for healthcheck
        volumes:
            - ./monitoring/hivemq-prometheus-extension:/opt/hivemq/extensions/hivemq-prometheus-extension
            - ./monitoring/hivemq-file-rbac-extension:/opt/hivemq/extensions/hivemq-file-rbac-extension
            - ./scripts/credentials_ingestion.xml:/opt/hivemq/extensions/hivemq-file-rbac-extension/conf/credentials.xml
        ulimits:
            nofile:
                soft: 500000
                hard: 500000


