BROKER_URL:  host.docker.internal
BROKER_PORT: 1883
BROKER_USERNAME: ${USERNAME}
BROKER_PASSWORD: ${PASSWORD}
CLIENT_ID: ${CLIENT_ID}
TOPIC: ${TOPIC}
QOS: ${QOS}
NR_OF_MESSAGES: 3
PUBLISH_INTERVAL: 1
TLS_ENABLED: False
CLEAN_START: True
RETAIN: False
REATTEMPTS: 0
KEEPALIVE: 60
TESTDATA_PATH: /app/data