BROKER_URL:  108.142.139.160
BROKER_PORT: 8085
CLIENT_ID: subscriber1
CA_CERT: cert.pem
TOPIC: site1/#
QOS: ${QOS}
TLS_ENABLED: True
CLEAN_START: True
RETAIN: False
REATTEMPTS: 0
KEEPALIVE: 60
TESTDATA_PATH: data/
