BROKER_URL:  localhost
BROKER_PORT: 1883
CLIENT_ID: subscriber1
BROKER_PASSWORD: ${PASSWORD2}
CA_CERT: cert.pem
TOPIC: site1/#
QOS: ${QOS}
TLS_ENABLED: True
CLEAN_START: True
RETAIN: False
REATTEMPTS: 0
KEEPALIVE: 60
TESTDATA_PATH: data/