BROKER_URL:  localhost
BROKER_PORT: 1883
BROKER_PASSWORD: ${PASSWORD}
CA_CERT: cert.pem
TOPIC: ${TOPIC}
QOS: ${QOS}
NR_OF_MESSAGES: 100
PUBLISH_INTERVAL: 1
TLS_ENABLED: True
CLEAN_START: True
RETAIN: False
REATTEMPTS: 0
KEEPALIVE: 60
TESTDATA_PATH: ${DATA}