BROKER_URL:  108.142.139.160
BROKER_PORT: 8084
CA_CERT: cert.pem
TOPIC: site1/
QOS: ${QOS}
NR_OF_MESSAGES: 1000
PUBLISH_INTERVAL: 1
TLS_ENABLED: True
CLEAN_START: True
RETAIN: False
REATTEMPTS: 0
KEEPALIVE: 60
TESTDATA_PATH: /app/data/provider2
