BROKER_URL:  host.docker.internal
BROKER_PORT: 1883
CLIENT_ID: ${CLIENT_ID}
TOPIC: ${TOPIC}
QOS: ${QOS}
NR_OF_MESSAGES: 4
PUBLISH_INTERVAL: 30
TLS_ENABLED: False
CLEAN_START: True
KEEPALIVE: 60
TESTDATA_PATH: /app/data