INGESTION_BROKER: SmartOceanBenchmark
INGESTION_BROKER_PORT: 1883
INGESTION_TLS: True
INGESTION_CA_CERT: cert.pem
CORE_BROKER: SmartOceanBenchmark
CORE_BROKER_PORT: 1885
INGESTION_TOPIC: site1/provider1/gateway1/hub1
CORE_TOPIC: site1/provider1/gateway1/hub1
QOS: ${QOS}

INGESTION_BROKER_CLIENT_ID: transformer1
CORE_BROKER_CLIENT_ID: transformer1

LOG_FILE: logs/log-transformer-provider1-gateway1-hub1.log