INGESTION_BROKER: ingestion-hivemq-broker
INGESTION_BROKER_PORT: 1883
CORE_BROKER: core-hivemq-broker
CORE_BROKER_PORT: 1884
INGESTION_TOPIC: smartocean/austevoll/aadi
CORE_TOPIC: smartocean/austevoll/aadi/raw
QOS: 2

INGESTION_BROKER_CLIENT_ID: aaditransformer
CORE_BROKER_CLIENT_ID: aaditransformer

LOG_FILE: logs/log-aadi-transformer-config1.log
