INGESTION_BROKER: localhost
INGESTION_BROKER_PORT: 1883
CORE_BROKER: localhost
CORE_BROKER_PORT: 1884
INGESTION_TOPIC: smartocean/austevoll/wsense/node2
CORE_TOPIC: smartocean/austevoll/wsense/node2/raw
QOS: ${QOS}

INGESTION_BROKER_CLIENT_ID: wsensetransformer2
CORE_BROKER_CLIENT_ID: wsensetransformer2

LOG_FILE: logs/log-wsense-hub2-transformer-config2.log