INGESTION_BROKER: localhost
INGESTION_BROKER_PORT: 1883
CORE_BROKER: localhost
CORE_BROKER_PORT: 1884
INGESTION_TOPIC: smartocean/austevoll/aadi/seaguardII_0002
CORE_TOPIC: smartocean/austevoll/aadi/seaguardII_0002/raw
QOS: ${QOS}

INGESTION_BROKER_CLIENT_ID: aaditransformer2
CORE_BROKER_CLIENT_ID: aaditransformer2

LOG_FILE: logs/log-aadi-hub2-transformer-config2.log