INGESTION_BROKER: localhost
INGESTION_BROKER_PORT: 1883
CORE_BROKER: localhost
CORE_BROKER_PORT: 1884
INGESTION_TOPIC: smartocean/austevoll/wsense/node1
CORE_TOPIC: smartocean/austevoll/wsense/node1/raw
QOS: ${QOS}

INGESTION_BROKER_CLIENT_ID: wsensetransformer1
CORE_BROKER_CLIENT_ID: wsensetransformer1

LOG_FILE: logs/log-wsense-hub1-transformer-config2.log