INGESTION_BROKER: SmartOceanBenchmark
INGESTION_BROKER_PORT: 1884
INGESTION_TLS: True
INGESTION_CA_CERT: ${CERT}
CORE_BROKER: core-hivemq-broker
CORE_BROKER_PORT: 1885
INGESTION_TOPIC: site1/provider2/gateway1/hub2
CORE_TOPIC: site1/provider2/gateway1/hub2
QOS: ${QOS}

INGESTION_BROKER_CLIENT_ID: transformer4
CORE_BROKER_CLIENT_ID: transformer4

LOG_FILE: logs/log-transformer-provider2-gateway1-hub2.log