# /tmp/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 # python openTelemetry auto-instrumentation receiver
  # Data sources: metrics -- for HiveMQ metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 15s
          static_configs:
            - targets: [core-hivemq-broker:9399]  # hivemq extension ${env:BROKER}
  hostmetrics:
    collection_interval: 5m # default = 1m
    initial_delay: 10s # default = 1s
    # root_path: <string>
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
      process:

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed
  file:
    path: ./telemetry.json
  # Data sources: metrics
  prometheus:
    endpoint: 0.0.0.0:8887
    namespace:

processors:
  batch:

extensions:
  health_check:
    endpoint: localhost:13133
  # zpages:

service:
  extensions: [health_check] #zpages
  pipelines:
    metrics:
      receivers: [ otlp, prometheus, hostmetrics ]
      exporters: [ prometheus ]
      processors: [ batch ]
#    logs:
#      receivers: [ otlp ]
#      exporters: [ debug ]
#      processors: [ batch ]
  telemetry:
    metrics:
      address: 0.0.0.0:8886
    logs:
      level: "info"

