global:
  scrape_interval: 5s

scrape_configs:  # use host.docker.internal when isolating docker networks

  - job_name: 'ingestion-service1' # HiveMQ Ingestion Broker for provider 1
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'SmartOceanBenchmark:8888' ]

  - job_name: 'ingestion-service2' # HiveMQ Ingestion Broker for provider 2
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'SmartOceanBenchmark:8889' ]

  - job_name: 'core-service' # HiveMQ + transformers
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'SmartOceanBenchmark:8887' ]

  - job_name: 'core-collector' # OpenTelemetry Collector
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'SmartOceanBenchmark:8886' ]

